# Generated by Django 4.0 on 2021-12-28 12:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('publish', models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 28, 12, 52, 57, 568361, tzinfo=utc))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField()),
                ('sumbnail_img', models.ImageField(upload_to='images')),
                ('status', models.CharField(choices=[('p', 'published'), ('d', 'draft')], max_length=1)),
            ],
        ),
    ]
