# Generated by Django 4.0 on 2021-12-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categorys',
            field=models.ManyToManyField(to='blog.Category', verbose_name='موضوع'),
        ),
    ]
