# Generated by Django 4.0 on 2021-12-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_categorys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='categorys',
            new_name='category',
        ),
    ]
