# Generated by Django 4.0 on 2022-01-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_article_is_special_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='آیا مقاله ویژه است ؟'),
        ),
    ]
