# Generated by Django 4.0.1 on 2022-01-25 10:50

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_article_is_special'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس آی پی')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='hits',
            field=models.ManyToManyField(blank=sqlalchemy.sql.expression.true, related_name='hits', to='blog.IpAddress', verbose_name='بازدیدها'),
        ),
    ]
