# Generated by Django 4.0.1 on 2022-01-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_ipaddress_article_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
    ]
